apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ include "host-path-provisioner.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "host-path-provisioner.name" . }}
    helm.sh/chart: {{ include "host-path-provisioner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "host-path-provisioner.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "host-path-provisioner.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: host-path-provisioner
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/host-path-provisioner"]
          args: ["-directory", "{{.Values.directory}}"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/lib/kubelet/host-path-provisioner-volumes
              name: host-path-provisioner-volume
      volumes:
        - name: host-path-provisioner-volume
          hostPath:
            path: {{.Values.directory}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
